# Spring properties
server:
  port: 28888
spring:
  application:
    name: bass2
  data:
    mongodb:
      #uri: ${DB_URL:mongodb://app:Gang!changer_Service0@wonger-mp:27018/gangchanger}
      uri: ${DB_URL:mongodb://app:Gang!changer_Service0@localhost:27017/gangchanger}
app:
  staticData:
    enableChromePluginLoading: false
    enableSlackPluginLoading: false
    enableShopifyPluginLoading: false
    enableCapterraPluginLoading: false
---
#Properties override when -Dspring.profiles.active=UNITTEST
spring:
  profiles: UNITTEST
  data:
    mongodb:
      uri: mongodb://localhost:27018/gangchanger
app:
  staticData:
    enableChromePluginLoading: false